from __future__ import annotations

from typing import Any, Protocol


class QueryRepository(Protocol):
    async def list_queries(self) -> list[dict[str, Any]]: ...
    async def get_query(self, name: str) -> dict[str, Any] | None: ...
    async def save_query(self, name: str, definition: dict[str, Any]) -> dict[str, Any]: ...
    async def remove_query(self, name: str) -> None: ...
    async def recent(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...
    async def count_recent(self, *args: Any, **kwargs: Any) -> int: ...


class GraylogRepository(Protocol):
    async def list_servers(self) -> list[dict[str, Any]]: ...
    async def get_server(self, server_id: int) -> dict[str, Any] | None: ...
    async def add_server(self, **values: Any) -> dict[str, Any]: ...
    async def update_server(self, server_id: int, **values: Any) -> dict[str, Any]: ...
    async def remove_server(self, server_id: int) -> None: ...


class AgentRepository(Protocol):
    async def list_agents(self) -> list[dict[str, Any]]: ...
    async def add_agent(self, **values: Any) -> dict[str, Any]: ...
    async def update_agent(self, agent_id: int, **values: Any) -> dict[str, Any]: ...
    async def remove_agent(self, agent_id: int) -> None: ...


class AuditRepository(Protocol):
    async def recent(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...
    async def count_recent(self, *args: Any, **kwargs: Any) -> int: ...


class AuditBackend(AuditRepository, Protocol):
    """Backend seam for replacing local SQLite audit storage."""


class ManagementRepository(GraylogRepository, AgentRepository, QueryRepository, AuditRepository, Protocol):
    """Complete repository port implemented by the bundled SQLite backend."""


class SecretProvider(Protocol):
    """Optional seam for external secret managers."""

    def encrypt(self, value: str) -> str: ...
    def decrypt(self, value: str) -> str: ...


class DistributedSessionStore(Protocol):
    """Optional drop-in contract for a multi-worker session implementation."""

    def create(self, now: float | None = None): ...
    def get(self, token: str | None, now: float | None = None): ...
    def revoke(self, token: str | None) -> None: ...
    def valid_csrf(self, token: str | None, supplied: str | None) -> bool: ...
